### ISSUE TITLE
Would anyone be free to talk about this repo and the paper behind it in a meetup on February or March?

### ISSUE THREAD

**Issue by bparbhu** [facebookresearch/brainmagick#6]
Hi All,

We're looking to talk about this repo and the paper behind it at a meetup I'm hosting remotely on February.
Would anyone be open to talking about it with us and exploring the paper in it's entirety to celebrate its achievement and the milestone it represents.

I run the NYC Brain-Computer Interface Meetup and we would love to talk to someone who contributed to this and can speak to the research as well.

Here's the link to the meetup. Let me know if this is possible.
https://www.meetup.com/NYC-BCI-meetup/

Big fan of your work here.

-Brian

**Comment by kingjr** [comment]
Sure, please contact us by email.

**Comment by bparbhu** [comment]
Awesome will do, is your email address in the paper?
